import Sidebar from '@/app/components/Sidebar';
import React from 'react';
export const metadata = {
    title: 'dashboard | user ',
    description: 'Generated by create next app',
  }


const dashboard_layout = ({children}) => {
    console.log("dashboard_layout Page rendered_2");

    return (
        
        <div className='flex container mx-auto'>
            {/* <h1 className="font-bold text-red-500">dashboard_layout</h1> */}
            <Sidebar></Sidebar>
            {children}
        </div>
    );
};

export default dashboard_layout;